//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey
    {
        public int id { get; set; }
        public Nullable<short> quality { get; set; }
        public Nullable<short> expertice { get; set; }
        public Nullable<short> culture { get; set; }
        public string comments { get; set; }
    }
}
